### ISSUE TITLE
page_token missing

### ISSUE THREAD

**Issue by tihomir-pesikan** [zoho/zohocrm-php-sdk-4.0#3]
Seems that there is no way to pass the page_token parameter, to retrieve more then 2000 records

**Comment by raja-7453** [comment]
Hi @tihomir-pesikan, kindly use the below code for the `page_token` param to retrieve more than 2000 records.
```php 
$paramInstance = new ParameterMap();
$paramInstance->add(GetRecordsParam::pageToken(), "xxx");
```

**Comment by tihomir-pesikan** [comment]
Hi @raja-7453, thank you for quick response, 
yet getting the following error message:
Fatal error: Uncaught Error: Call to undefined method com\zoho\crm\api\record\GetRecordsParam::pageToken() in ...

**Comment by raja-7453** [comment]
We're currently working on a major SDK version, in which we will also be supporting this new param. 
Till then, please use this.
Import this header `use com\zoho\crm\api\Param;`
```php
$paramInstance->add(new Param("page_token", String::class), "xxx");
```
Please forward any SDK-related queries to [support@zohocrm.com](mailto:support@zohocrm.com) and we'll take things forward.
